### ISSUE TITLE
Container crashes when initiating stream with no subtitles

### ISSUE THREAD

**Issue by koszanski** [gurrrrrrett3/vrchat-jellyfin#11]
Upon trying to playback a stream generated with the "no subtitles" option in the GUI, the container hangs.
Have done this internally, reverse proxy doesn't appear to be a factor.

output of `docker attach`:

```
/app/dist/jellyfin/client.js:100
            url.searchParams.set("SubtitleStreamIndex", options.subtitleStreamIndex.toString());
                                                                                    ^

TypeError: Cannot read properties of null (reading 'toString')
    at JellyfinClient.getVideoStream (/app/dist/jellyfin/client.js:100:85)
    at /app/dist/webserver/index.js:54:44
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/app/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/app/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at /app/node_modules/express/lib/router/index.js:284:15
    at param (/app/node_modules/express/lib/router/index.js:365:14)
    at param (/app/node_modules/express/lib/router/index.js:376:14)
    at Function.process_params (/app/node_modules/express/lib/router/index.js:421:3)

Node.js v22.11.0
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by gurrrrrrett3** [comment]
somehow missed this issue, will take a look at it tomorrow! sorry about that

**Comment by gurrrrrrett3** [comment]
sorry, fixed in #12, forgot to close
