### ISSUE TITLE
npm run build fails

### ISSUE THREAD

**Issue by noideaman** [gurrrrrrett3/vrchat-jellyfin#2]
looks like the script to build is missing or not refrenced properly?

in a docker container if wondering why it is using root
```
pm error Missing script: "build"
npm error
npm error To see a list of scripts, run:
npm error   npm run
npm error A complete log of this run can be found in: /root/.npm/_logs/2024-06-18T21_18_54_064Z-debug-0.log
```

**Comment by noideaman** [comment]
full output of the command npm run build
```
0 verbose cli /usr/bin/node /usr/bin/npm
1 info using npm@10.8.0
2 info using node@v21.7.3
3 silly config load:file:/usr/lib/node_modules/npm/npmrc
4 silly config load:file:/vrchat-jellyfin/.npmrc
5 silly config load:file:/root/.npmrc
6 silly config load:file:/etc/npmrc
7 verbose title npm run build
8 verbose argv "run" "build"
9 verbose logfile logs-max:10 dir:/root/.npm/_logs/2024-06-18T21_23_03_005Z-
10 verbose logfile /root/.npm/_logs/2024-06-18T21_23_03_005Z-debug-0.log
11 silly logfile done cleaning log files
12 verbose stack Error: Missing script: "build"
12 verbose stack
12 verbose stack To see a list of scripts, run:
12 verbose stack   npm run
12 verbose stack     at #run (/usr/lib/node_modules/npm/lib/commands/run-script.js:110:13)
12 verbose stack     at async RunScript.exec (/usr/lib/node_modules/npm/lib/commands/run-script.js:39:7)
12 verbose stack     at async Npm.exec (/usr/lib/node_modules/npm/lib/npm.js:207:9)
12 verbose stack     at async module.exports (/usr/lib/node_modules/npm/lib/cli/entry.js:74:5)
13 error Missing script: "build"
13 error
13 error To see a list of scripts, run:
13 error   npm run
14 verbose cwd /vrchat-jellyfin
15 verbose os Linux 6.9.5-1.el9.elrepo.x86_64
16 verbose node v21.7.3
17 verbose npm  v10.8.0
18 verbose exit 1
19 verbose code 1
20 error A complete log of this run can be found in: /root/.npm/_logs/2024-06-18T21_23_03_005Z-debug-0.log
```
